### ISSUE TITLE
Support authorization for ref loader

### ISSUE THREAD

**Issue by mih-kopylov** [asyncapi/parser-go#146]
### Reason/Context
If `$ref` references a file via HTTP(S) that is protected via authorization, it prints a misleading error messages and stops:
```
yaml: line 4: mapping values are not allowed in this context
```

The core reason is in fact that jsonpath.RefLoader doesn't support authorization when its http client makes a GET request.

### Description
The possible workarounds:
#### add `--authorization` CLI flag that will be used for all requests and added as a `Authorization` header
Drawback: if OpenApi file contains references to several hosts, they might have different authorization or might be public

```
api-parser --authorization 'Bearer AAA` file.yaml
```

#### pass `authorization` file to the CLI that will contain authorization methods/values for different hosts or even different paths

Just a custom header for all requests to the host:
```
- host: github.com
  header: Bearer AAA
```

Basic auth for all requests to the host:
```
- host: bitbucket.org
  basic:
    username: user
    password: pass
```

OAuth2 client_credentials for all requests to the host:
```
- host: custom.com
  oauth:
    tokenEndpoint: https://custom.com/oauth/token
    clientId: client
    secret: pass
```

Basic auth for references that start with the path:
```
- path: bitbucket.org/workspace/
  basic:
    username: user
    password: pass
```
